use database::{create_http_client, load_settings, AppDatabase};
use parking_lot::Mutex;
use std::collections::HashMap;
use tauri::Manager;

mod commands;
mod database;
mod discord;
mod error;
mod models;
mod state;
mod steam_watch;
mod wine;

use commands::*;
use models::*;
use state::AppState;

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    let app_db = match AppDatabase::open() {
        Ok(db) => db,
        Err(e) => {
            log::error!("Failed to open database, falling back to in-memory storage: {e}");
            AppDatabase::open_in_memory().expect("in-memory database must open")
        }
    };

    let http_client = create_http_client();

    let state = AppState {
        running_game: Mutex::new(None),
        settings: Mutex::new(load_settings()),
        vn_mem_cache: Mutex::new(HashMap::new()),
        char_mem_cache: Mutex::new(HashMap::new()),
        wine_versions: Mutex::new(Vec::new()),
        http_client,
        discord_rpc: discord::DiscordRpc::new(),
    };

    let builder = tauri_specta::Builder::<tauri::Wry>::new()
        .commands(tauri_specta::collect_commands![
            init_app,
            get_all_games,
            add_local_game,
            remove_game,
            update_game,
            search_vndb,
            fetch_vndb_detail,
            fetch_vndb_characters,
            clear_vndb_cache,
            clear_all_cache,
            get_settings,
            save_vndb_token,
            clear_vndb_token,
            set_blur_nsfw,
            vndb_auth_check,
            vndb_get_user_vn,
            vndb_set_status,
            vndb_set_vote,
            vndb_remove_vote,
            launch_game,
            stop_tracking,
            poll_running_game,
            get_elapsed_time,
            set_game_hidden,
            set_discord_rpc_enabled,
            set_discord_rpc_buttons,
            get_platform,
            get_available_wine_versions,
            refresh_wine_versions,
            get_default_wine_settings,
            get_default_prefix_path,
            save_game_wine_settings,
            save_global_wine_defaults,
            is_steam_runtime_available,
            validate_wine_binary,
            read_log_file,
            get_log_path,
        ])
        .typ::<GameMetadata>()
        .typ::<DailyPlaytimeData>()
        .typ::<VndbSearchResult>()
        .typ::<VndbImage>()
        .typ::<VndbVnDetail>()
        .typ::<VndbTag>()
        .typ::<VndbCharacter>()
        .typ::<VndbTrait>()
        .typ::<VndbCharacterVn>()
        .typ::<VndbUserListItem>()
        .typ::<VndbLabel>()
        .typ::<VndbAuthInfo>()
        .typ::<AppSettings>()
        .typ::<WineType>()
        .typ::<WineSource>()
        .typ::<GameType>()
        .typ::<WineVersion>()
        .typ::<WineSettings>()
        .dangerously_cast_bigints_to_number();

    #[cfg(debug_assertions)]
    builder
        .export(
            specta_typescript::Typescript::new()
                .header("// Auto-generated by tauri-specta. Do not edit manually.\n"),
            "../src/bindings.ts",
        )
        .expect("Failed to export TypeScript bindings");

    tauri::Builder::default()
        .plugin(tauri_plugin_dialog::init())
        .plugin(tauri_plugin_fs::init())
        .plugin(tauri_plugin_shell::init())
        .plugin(tauri_plugin_updater::Builder::new().build())
        .plugin(tauri_plugin_process::init())
        .invoke_handler(builder.invoke_handler())
        .manage(state)
        .manage(app_db)
        .setup(move |app| {
            builder.mount_events(app);
            app.handle().plugin(
                tauri_plugin_log::Builder::default()
                    .level(log::LevelFilter::Info)
                    .build(),
            )?;
            let app_handle = app.handle().clone();
            std::thread::spawn(move || {
                #[cfg(target_os = "linux")]
                let versions = wine::get_all_wine_versions();
                #[cfg(not(target_os = "linux"))]
                let versions = Vec::new();
                let count = versions.len();
                *app_handle.state::<AppState>().wine_versions.lock() = versions;
                log::info!("Wine runner scan finished: {count} versions");
            });
            Ok(())
        })
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::error::AppError;

    #[test]
    fn test_specta_export_covers_domain_types() {
        let builder = tauri_specta::Builder::<tauri::Wry>::new()
            .dangerously_cast_bigints_to_number()
            .typ::<GameMetadata>()
            .typ::<AppError>();
        let path =
            std::env::temp_dir().join(format!("poketto-bindings-test-{}.ts", std::process::id()));
        builder
            .export(
                specta_typescript::Typescript::new().header("// test\n"),
                &path,
            )
            .expect("specta export must succeed");
        let content = std::fs::read_to_string(&path).expect("exported bindings readable");
        assert!(content.contains("export type GameMetadata"));
        assert!(content.contains("steam_app_id"));
        assert!(content.contains("play_time: number"));
        assert!(content.contains("{ kind: \"Database\"; message: string }"));
        std::fs::remove_file(&path).ok();
    }
}
