use parking_lot::Mutex;
use std::collections::HashMap;

mod commands;
mod database;
mod discord;
mod error;
mod models;
mod state;
mod wine;

use commands::*;
use database::{create_cache_db, create_http_client, load_games, load_settings};
use models::*;
use state::AppState;

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    let db = create_cache_db();

    let games = match load_games() {
        Ok(g) => g,
        Err(e) => {
            eprintln!("Error loading games: {}", e);
            Vec::new()
        }
    };

    let http_client = create_http_client();

    let state = AppState {
        games: Mutex::new(games),
        running_game: Mutex::new(None),
        settings: Mutex::new(load_settings()),
        vn_mem_cache: Mutex::new(HashMap::new()),
        char_mem_cache: Mutex::new(HashMap::new()),
        http_client,
        db,
        discord_rpc: discord::DiscordRpc::new(),
    };

    let builder = tauri_specta::Builder::<tauri::Wry>::new()
        .commands(tauri_specta::collect_commands![
            init_app,
            get_all_games,
            add_local_game,
            remove_game,
            update_game,
            search_vndb,
            fetch_vndb_detail,
            fetch_vndb_characters,
            clear_vndb_cache,
            clear_all_cache,
            get_settings,
            save_vndb_token,
            clear_vndb_token,
            set_blur_nsfw,
            vndb_auth_check,
            vndb_get_user_vn,
            vndb_set_status,
            vndb_set_vote,
            vndb_remove_vote,
            launch_game,
            stop_tracking,
            poll_running_game,
            get_elapsed_time,
            set_game_hidden,
            set_discord_rpc_enabled,
            set_discord_rpc_buttons,
            get_platform,
            get_available_wine_versions,
            get_default_wine_settings,
            get_default_prefix_path,
            save_game_wine_settings,
            save_global_wine_defaults,
            is_steam_runtime_available,
            validate_wine_binary,
        ])
        .typ::<GameMetadata>()
        .typ::<DailyPlaytimeData>()
        .typ::<VndbSearchResult>()
        .typ::<VndbImage>()
        .typ::<VndbVnDetail>()
        .typ::<VndbTag>()
        .typ::<VndbCharacter>()
        .typ::<VndbTrait>()
        .typ::<VndbCharacterVn>()
        .typ::<VndbUserListItem>()
        .typ::<VndbLabel>()
        .typ::<VndbAuthInfo>()
        .typ::<AppSettings>()
        .typ::<WineType>()
        .typ::<GameType>()
        .typ::<WineVersion>()
        .typ::<WineSettings>();

    #[cfg(debug_assertions)]
    builder
        .export(
            specta_typescript::Typescript::default()
                .bigint(specta_typescript::BigIntExportBehavior::Number)
                .header("// Auto-generated by tauri-specta. Do not edit manually.\n"),
            "../src/bindings.ts",
        )
        .expect("Failed to export TypeScript bindings");

    tauri::Builder::default()
        .plugin(tauri_plugin_dialog::init())
        .plugin(tauri_plugin_fs::init())
        .plugin(tauri_plugin_shell::init())
        .plugin(tauri_plugin_updater::Builder::new().build())
        .plugin(tauri_plugin_process::init())
        .invoke_handler(builder.invoke_handler())
        .manage(state)
        .setup(move |app| {
            builder.mount_events(app);
            app.handle().plugin(
                tauri_plugin_log::Builder::default()
                    .level(log::LevelFilter::Info)
                    .build(),
            )?;
            Ok(())
        })
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
