// Auto-generated by tauri-specta. Do not edit manually.

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	initApp: () => __TAURI_INVOKE<void>("init_app"),
	getAllGames: () => __TAURI_INVOKE<GameMetadata[]>("get_all_games"),
	addLocalGame: (path: string) => typedError<GameMetadata, AppError>(__TAURI_INVOKE("add_local_game", { path })),
	removeGame: (id: string) => typedError<null, AppError>(__TAURI_INVOKE("remove_game", { id })),
	updateGame: (game: GameMetadata) => typedError<null, AppError>(__TAURI_INVOKE("update_game", { game })),
	searchVndb: (query: string) => typedError<VndbSearchResult[], AppError>(__TAURI_INVOKE("search_vndb", { query })),
	fetchVndbDetail: (vndbId: string, forceRefresh: boolean | null) => typedError<VndbVnDetail, AppError>(__TAURI_INVOKE("fetch_vndb_detail", { vndbId, forceRefresh })),
	fetchVndbCharacters: (vndbId: string, forceRefresh: boolean | null) => typedError<VndbCharacter[], AppError>(__TAURI_INVOKE("fetch_vndb_characters", { vndbId, forceRefresh })),
	clearVndbCache: (vndbId: string) => typedError<null, AppError>(__TAURI_INVOKE("clear_vndb_cache", { vndbId })),
	clearAllCache: () => typedError<null, AppError>(__TAURI_INVOKE("clear_all_cache")),
	getSettings: () => __TAURI_INVOKE<AppSettings>("get_settings"),
	saveVndbToken: (token: string) => typedError<null, AppError>(__TAURI_INVOKE("save_vndb_token", { token })),
	clearVndbToken: () => typedError<null, AppError>(__TAURI_INVOKE("clear_vndb_token")),
	setBlurNsfw: (blur: boolean) => typedError<null, AppError>(__TAURI_INVOKE("set_blur_nsfw", { blur })),
	vndbAuthCheck: () => typedError<VndbAuthInfo, AppError>(__TAURI_INVOKE("vndb_auth_check")),
	vndbGetUserVn: (vndbId: string) => typedError<{
	id: string,
	vote: number | null,
	labels: VndbLabel[] | null,
	started: string | null,
	finished: string | null,
} | null, AppError>(__TAURI_INVOKE("vndb_get_user_vn", { vndbId })),
	vndbSetStatus: (vndbId: string, labelId: number) => typedError<null, AppError>(__TAURI_INVOKE("vndb_set_status", { vndbId, labelId })),
	vndbSetVote: (vndbId: string, vote: number) => typedError<null, AppError>(__TAURI_INVOKE("vndb_set_vote", { vndbId, vote })),
	vndbRemoveVote: (vndbId: string) => typedError<null, AppError>(__TAURI_INVOKE("vndb_remove_vote", { vndbId })),
	launchGame: (id: string) => typedError<null, AppError>(__TAURI_INVOKE("launch_game", { id })),
	stopTracking: () => typedError<number, AppError>(__TAURI_INVOKE("stop_tracking")),
	pollRunningGame: () => __TAURI_INVOKE<string | null>("poll_running_game"),
	getElapsedTime: () => __TAURI_INVOKE<number>("get_elapsed_time"),
	setGameHidden: (id: string, hidden: boolean) => typedError<null, AppError>(__TAURI_INVOKE("set_game_hidden", { id, hidden })),
	setDiscordRpcEnabled: (enabled: boolean) => typedError<null, AppError>(__TAURI_INVOKE("set_discord_rpc_enabled", { enabled })),
	setDiscordRpcButtons: (vndbGame: boolean, vndbProfile: boolean, github: boolean) => typedError<null, AppError>(__TAURI_INVOKE("set_discord_rpc_buttons", { vndbGame, vndbProfile, github })),
	getPlatform: () => __TAURI_INVOKE<string>("get_platform"),
	getAvailableWineVersions: () => __TAURI_INVOKE<WineVersion[]>("get_available_wine_versions"),
	refreshWineVersions: () => typedError<WineVersion[], AppError>(__TAURI_INVOKE("refresh_wine_versions")),
	getDefaultWineSettings: () => __TAURI_INVOKE<WineSettings>("get_default_wine_settings"),
	getDefaultPrefixPath: (gameId: string) => __TAURI_INVOKE<string>("get_default_prefix_path", { gameId }),
	saveGameWineSettings: (gameId: string, wineSettings: WineSettings) => typedError<null, AppError>(__TAURI_INVOKE("save_game_wine_settings", { gameId, wineSettings })),
	saveGlobalWineDefaults: (prefix: string | null, binary: string | null, useSteamRuntime: boolean) => typedError<null, AppError>(__TAURI_INVOKE("save_global_wine_defaults", { prefix, binary, useSteamRuntime })),
	isSteamRuntimeAvailable: () => __TAURI_INVOKE<boolean>("is_steam_runtime_available"),
	validateWineBinary: (binaryPath: string) => typedError<string, AppError>(__TAURI_INVOKE("validate_wine_binary", { binaryPath })),
	readLogFile: (limit: number | null) => typedError<string[], AppError>(__TAURI_INVOKE("read_log_file", { limit })),
	getLogPath: () => typedError<string, AppError>(__TAURI_INVOKE("get_log_path")),
};

/* Types */
export type AppError = { kind: "Io"; message: string } | { kind: "Json"; message: string } | { kind: "Http"; message: string } | { kind: "Database"; message: string } | { kind: "NotFound"; message: string } | { kind: "VndbApi"; message: string } | { kind: "AuthRequired"; message: string } | { kind: "ProcessLaunch"; message: string } | { kind: "Validation"; message: string };

export type AppSettings = {
	vndb_token: string | null,
	vndb_user_id: string | null,
	blur_nsfw: boolean,
	discord_rpc_enabled?: boolean,
	discord_btn_vndb_game?: boolean,
	discord_btn_vndb_profile?: boolean,
	discord_btn_github?: boolean,
	default_wine_prefix?: string | null,
	default_wine_binary?: string | null,
	use_steam_runtime?: boolean,
};

export type DailyPlaytimeData = {
	games: { [key in string]: { [key in string]: number } },
};

export type GameMetadata = {
	id: string,
	title: string,
	path: string,
	vndb_id: string | null,
	steam_app_id?: string | null,
	cover_url: string | null,
	play_time: number,
	is_finished: boolean,
	last_played?: string | null,
	is_hidden?: boolean,
	show_spoilers?: boolean,
	game_type?: GameType | null,
	wine_settings?: WineSettings | null,
};

export type GameType = "WindowsExe" | "LinuxNative";

export type VndbAuthInfo = {
	id: string,
	username: string,
};

export type VndbCharacter = {
	id: string,
	name: string,
	original: string | null,
	aliases: string[] | null,
	image: VndbImage | null,
	description: string | null,
	blood_type: string | null,
	height: number | null,
	weight: number | null,
	bust: number | null,
	waist: number | null,
	hips: number | null,
	cup: string | null,
	age: number | null,
	birthday: number[] | null,
	sex: string[] | null,
	vns: VndbCharacterVn[] | null,
	traits: VndbTrait[] | null,
};

export type VndbCharacterVn = {
	id: string,
	role: string,
	spoiler?: number,
};

export type VndbImage = {
	url: string,
	sexual?: number | null,
	violence?: number | null,
};

export type VndbLabel = {
	id: number,
	label: string,
};

export type VndbProducer = {
	id: string,
	name: string,
};

export type VndbSearchResult = {
	id: string,
	title: string,
	image: VndbImage | null,
	released: string | null,
	rating: number | null,
};

export type VndbTag = {
	id: string,
	name: string,
	rating: number | null,
	spoiler?: number,
};

export type VndbTrait = {
	id: string,
	name: string,
	group_id: string | null,
	group_name: string | null,
	spoiler?: number,
};

export type VndbUserListItem = {
	id: string,
	vote: number | null,
	labels: VndbLabel[] | null,
	started: string | null,
	finished: string | null,
};

export type VndbVnDetail = {
	id: string,
	title: string,
	image: VndbImage | null,
	released: string | null,
	rating: number | null,
	description: string | null,
	length: number | null,
	length_minutes: number | null,
	tags: VndbTag[] | null,
	developers: VndbProducer[] | null,
};

/**  Per-game Wine/Proton settings */
export type WineSettings = {
	use_global_prefix: boolean,
	wine_prefix: string | null,
	wine_version: string | null,
	wine_type: WineType | null,
	use_steam_runtime: boolean,
	env_vars?: { [key in string]: string },
};

export type WineSource = "System" | "Opt" | "Steam" | "SteamFlatpak" | "Lutris" | "Bottles" | "BottlesFlatpak" | "Custom";

export type WineType = "Wine" | "WineGE" | "WineStaging" | "WineTKG" | "Proton" | "ProtonGE" | "ProtonCachyOS" | "ProtonTKG" | "Lutris" | "Bottles" | "Custom";

export type WineVersion = {
	name: string,
	binary_path: string,
	lib_path: string | null,
	wine_type: WineType,
	version: string | null,
	source: WineSource | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

