// Auto-generated by tauri-specta. Do not edit manually.

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async initApp() : Promise<void> {
    await TAURI_INVOKE("init_app");
},
async getAllGames() : Promise<GameMetadata[]> {
    return await TAURI_INVOKE("get_all_games");
},
async addLocalGame(path: string) : Promise<Result<GameMetadata, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_local_game", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async removeGame(id: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_game", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateGame(game: GameMetadata) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_game", { game }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async searchVndb(query: string) : Promise<Result<VndbSearchResult[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("search_vndb", { query }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async fetchVndbDetail(vndbId: string, forceRefresh: boolean | null) : Promise<Result<VndbVnDetail, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("fetch_vndb_detail", { vndbId, forceRefresh }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async fetchVndbCharacters(vndbId: string, forceRefresh: boolean | null) : Promise<Result<VndbCharacter[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("fetch_vndb_characters", { vndbId, forceRefresh }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clearVndbCache(vndbId: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clear_vndb_cache", { vndbId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clearAllCache() : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clear_all_cache") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSettings() : Promise<AppSettings> {
    return await TAURI_INVOKE("get_settings");
},
async saveVndbToken(token: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_vndb_token", { token }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clearVndbToken() : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clear_vndb_token") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setBlurNsfw(blur: boolean) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_blur_nsfw", { blur }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async vndbAuthCheck() : Promise<Result<VndbAuthInfo, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("vndb_auth_check") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async vndbGetUserVn(vndbId: string) : Promise<Result<VndbUserListItem | null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("vndb_get_user_vn", { vndbId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async vndbSetStatus(vndbId: string, labelId: number) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("vndb_set_status", { vndbId, labelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async vndbSetVote(vndbId: string, vote: number) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("vndb_set_vote", { vndbId, vote }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async vndbRemoveVote(vndbId: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("vndb_remove_vote", { vndbId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async launchGame(id: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("launch_game", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async stopTracking() : Promise<Result<number, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_tracking") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async pollRunningGame() : Promise<string | null> {
    return await TAURI_INVOKE("poll_running_game");
},
async getElapsedTime() : Promise<number> {
    return await TAURI_INVOKE("get_elapsed_time");
},
async setGameHidden(id: string, hidden: boolean) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_game_hidden", { id, hidden }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setDiscordRpcEnabled(enabled: boolean) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_discord_rpc_enabled", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setDiscordRpcButtons(vndbGame: boolean, vndbProfile: boolean, github: boolean) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_discord_rpc_buttons", { vndbGame, vndbProfile, github }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getPlatform() : Promise<string> {
    return await TAURI_INVOKE("get_platform");
},
async getAvailableWineVersions() : Promise<WineVersion[]> {
    return await TAURI_INVOKE("get_available_wine_versions");
},
async refreshWineVersions() : Promise<Result<WineVersion[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("refresh_wine_versions") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getDefaultWineSettings() : Promise<WineSettings> {
    return await TAURI_INVOKE("get_default_wine_settings");
},
async getDefaultPrefixPath(gameId: string) : Promise<string> {
    return await TAURI_INVOKE("get_default_prefix_path", { gameId });
},
async saveGameWineSettings(gameId: string, wineSettings: WineSettings) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_game_wine_settings", { gameId, wineSettings }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveGlobalWineDefaults(prefix: string | null, binary: string | null, useSteamRuntime: boolean) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_global_wine_defaults", { prefix, binary, useSteamRuntime }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async isSteamRuntimeAvailable() : Promise<boolean> {
    return await TAURI_INVOKE("is_steam_runtime_available");
},
async validateWineBinary(binaryPath: string) : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("validate_wine_binary", { binaryPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async readLogFile(limit: number | null) : Promise<Result<string[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_log_file", { limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getLogPath() : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_log_path") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type AppError = { kind: "Io"; message: string } | { kind: "Json"; message: string } | { kind: "Http"; message: string } | { kind: "Database"; message: string } | { kind: "Bincode"; message: string } | { kind: "NotFound"; message: string } | { kind: "VndbApi"; message: string } | { kind: "AuthRequired"; message: string } | { kind: "ProcessLaunch"; message: string } | { kind: "Validation"; message: string }
export type AppSettings = { vndb_token: string | null; vndb_user_id: string | null; blur_nsfw: boolean; discord_rpc_enabled?: boolean; discord_btn_vndb_game?: boolean; discord_btn_vndb_profile?: boolean; discord_btn_github?: boolean; default_wine_prefix?: string | null; default_wine_binary?: string | null; use_steam_runtime?: boolean }
export type DailyPlaytimeData = { games: Partial<{ [key in string]: Partial<{ [key in string]: number }> }> }
export type GameMetadata = { id: string; title: string; path: string; vndb_id: string | null; cover_url: string | null; play_time: number; is_finished: boolean; last_played?: string | null; is_hidden?: boolean; show_spoilers?: boolean; game_type?: GameType | null; wine_settings?: WineSettings | null }
export type GameType = "WindowsExe" | "LinuxNative"
export type VndbAuthInfo = { id: string; username: string }
export type VndbCharacter = { id: string; name: string; original: string | null; aliases: string[] | null; image: VndbImage | null; description: string | null; blood_type: string | null; height: number | null; weight: number | null; bust: number | null; waist: number | null; hips: number | null; cup: string | null; age: number | null; birthday: number[] | null; sex: string[] | null; vns: VndbCharacterVn[] | null; traits: VndbTrait[] | null }
export type VndbCharacterVn = { id: string; role: string; spoiler?: number }
export type VndbImage = { url: string; sexual?: number; violence?: number }
export type VndbLabel = { id: number; label: string }
export type VndbProducer = { id: string; name: string }
export type VndbSearchResult = { id: string; title: string; image: VndbImage | null; released: string | null; rating: number | null }
export type VndbTag = { id: string; name: string; rating: number; spoiler?: number }
export type VndbTrait = { id: string; name: string; group_id: string | null; group_name: string | null; spoiler?: number }
export type VndbUserListItem = { id: string; vote: number | null; labels: VndbLabel[] | null; started: string | null; finished: string | null }
export type VndbVnDetail = { id: string; title: string; image: VndbImage | null; released: string | null; rating: number | null; description: string | null; length: number | null; length_minutes: number | null; tags: VndbTag[] | null; developers: VndbProducer[] | null }
/**
 * Per-game Wine/Proton settings
 */
export type WineSettings = { use_global_prefix: boolean; wine_prefix: string | null; wine_version: string | null; wine_type: WineType | null; use_steam_runtime: boolean; env_vars?: Partial<{ [key in string]: string }> }
export type WineSource = "System" | "Opt" | "Steam" | "SteamFlatpak" | "Lutris" | "Bottles" | "BottlesFlatpak" | "Custom"
export type WineType = "Wine" | "WineGE" | "WineStaging" | "WineTKG" | "Proton" | "ProtonGE" | "ProtonCachyOS" | "ProtonTKG" | "Lutris" | "Bottles" | "Custom"
export type WineVersion = { name: string; binary_path: string; lib_path: string | null; wine_type: WineType; version: string | null; source: WineSource | null }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
