import { Theme } from "tokens.slint";
import { GameCardData } from "components/GameCard.slint";
import { LibraryView } from "views/LibraryView.slint";

export component AppWindow inherits Window {
    title: "Poketto";
    min-width: 800px;
    min-height: 600px;
    background: Theme.bg-dark;

    in-out property <[GameCardData]> games;
    in-out property <string> query;
    in-out property <int> active-filter;

    callback game-clicked(string);
    callback search-accepted(string);
    callback filter-changed(int);

    LibraryView {
        width: 100%;
        height: 100%;
        games <=> root.games;
        query <=> root.query;
        active-filter <=> root.active-filter;
        game-clicked(id) => { root.game-clicked(id); }
        search-accepted(query) => { root.search-accepted(query); }
        filter-changed(index) => { root.filter-changed(index); }
    }
}
