export global Theme {
    out property <color> bg-dark: #0f1115;
    out property <color> surface: #181a20;
    out property <color> surface-hover: #222630;
    out property <color> primary: #a277ff;
    out property <color> text-primary: #ededed;
    out property <color> text-muted: #8e94a4;
    out property <color> border: #282c37;

    out property <length> radius-sm: 6px;
    out property <length> radius-md: 10px;
    out property <length> pad-sm: 8px;
    out property <length> pad-md: 14px;
    out property <length> pad-lg: 20px;
}
